export const PERMISSIONS = [
  "system.manage",
  "system.audit.read",
  "system.settings.manage",
  "users.manage",
  "roles.manage",
  "permissions.manage",
  "employees.read",
  "employees.manage",
  "employees.documents.read",
  "employees.documents.manage",
  "attendance.self",
  "attendance.read",
  "attendance.manage",
  "attendance.approve",
  "attendance.correct",
  "leave.self",
  "leave.read",
  "leave.manage",
  "leave.approve",
  "nte.self",
  "nte.read",
  "nte.manage",
  "cash_advance.self",
  "cash_advance.read",
  "cash_advance.manage",
  "cash_advance.approve",
  "payroll.self",
  "payroll.read",
  "payroll.manage",
  "payroll.approve",
  "crm.read",
  "crm.manage",
  "crm.reports",
  "recruitment.read",
  "recruitment.manage",
  "clients.read",
  "clients.manage",
  "clients.employee_visibility",
  "tickets.self",
  "tickets.read",
  "tickets.manage",
  "billing.read",
  "billing.manage",
  "performance.self",
  "performance.read",
  "performance.manage",
  "reports.read",
  "reports.export",
  "cms.manage",
  "approvals.act",
] as const;

export type PermissionCode = (typeof PERMISSIONS)[number];

export const BEEPA_ORG_ID = "11111111-1111-1111-1111-111111111111";
